### ISSUE TITLE
misuse of singleflight.Group

### ISSUE THREAD

**Issue by Reasno** [woorui/gorm-cache#1]
```go
		g.requestGroup.Do(cachekey, func() (interface{}, error) {
			queryFromDB(db)
			return nil, db.Error
		})
```

当缓存失效时，这里在多并发的时候只有其中一个请求能拿到数据，其他请求会拿不到。

**Comment by Reasno** [comment]
根据singleflight.Group的文档，并发的第二个请求会直接获取第一个请求的结果，但是不会重复执行。可是这里没有返回结果。

Do executes and returns the results of the given function, making sure that only one execution is in-flight for a given key at a time. If a duplicate comes in, the duplicate caller waits for the original to complete and receives the same results. The return value shared indicates whether v was given to multiple callers.

**Comment by Reasno** [comment]
又看了一下后面还有一个queryFromDB。这样的话第一次请求会queryFromDB执行两次。

**Comment by woorui** [comment]
#2 我这样写怎么样
